### ISSUE TITLE
完善文档

### ISSUE THREAD

**Issue by duchenpaul** [lingex/G610Rebuild#1]
您好, 我在张大妈看到你的文章, 看起来很不错, 估计是全网最深度的DIY了, 但是我是ST32小白, 不太懂怎么刷机, 
所以, 可以有空出个详细教程, 包括接线方式和固件之类的么?
谢谢! 期待你能出更多的固件

**Comment by lingex** [comment]
完善了下文档。刷机其实很容易的，对着STLINK和板上的丝印标识，一一对应着连起来就可以了。

不过小白的话建议最好先买块小开发板之类的练练手哈。编译环境和下载工具挺多教程的，我就不写了。

**Comment by duchenpaul** [comment]
谢谢, 看上去很全, 我熟悉ttl刷机 - 刷路由那种, ST32完全没有接触过, 有空研究下你的教程, 不懂再问 谢谢啦
