### ISSUE TITLE
老哥 要不试试 刷接收器 固件？ 刷g913  

### ISSUE THREAD

**Issue by willshion** [lingex/G610Rebuild#2]
能不能加V 请教 13450808903 
有点觉得老哥牛逼啊

**Comment by lingex** [comment]
我没有这个型号的，你准备折腾啥功能？

现在已经吃灰了，键帽实在太差，扫个灰都能弹飞。

**Comment by lingex** [comment]
> 能不能加V 请教 13450808903 有点觉得老哥牛逼啊

我没有这个型号的，你准备折腾啥功能？

现在已经吃灰了，键帽实在太差，扫个灰都能弹飞。
