### ISSUE TITLE
Feature request: adding bluetooth

### ISSUE THREAD

**Issue by t3st-account** [lingex/G610Rebuild#3]
hi, I am looking ito your firmware, and I was wondering if it is feasible add bluetooth while maintaining usb.

I want to use this keyboard with multiple computers without replugging usb...
 Iwas thinking of using a uart to bluetooth module, and a spechial key-combo to enable/disable BT.

I am willing to help/fork but I would like an introduction to the structure of the code..

**Comment by lingex** [comment]
@t3st-account
That seemed feasible. 
You may have to modify 2 files of the code.

1) main.c: 255     there's a variable named "keyChange", which means one or more key state changes, 
  you may send data here via the UART.  (eg. HAL_UART_Transmit(&huart1, (uint8_t *)buff, 64, 100);)
  the format of the UART message would fix your BT module definition.

2) keyboard.c: 198  there's a sample about a key-combo action.



some introduction of the user codes:
keyboard.c: the physical layer of the key matrix, check keys state, debounce, key-combo action, and so on;
matrix_led.c: the backlights;
state_led.c: the LOGO and three locks led.
main.c: kinds of peripheral initiation, key functions, and some interrupt tasks.

**Comment by t3st-account** [comment]
Thank you, I managed to flash my keyboard with your firmaware.
I also forked this repo.
The one thoing that I do not get is how to flash the keyboard in DFU mode (after initial flashing with ST-Link)

**Comment by lingex** [comment]
1. compile the source code to a .hex (or .bin) file using gcc-arm-none-eabi (free) or Keil MDK (with a CE lic)
2. convert the .hex / .bin file into a .dfu file using hex2dfu, (https://github.com/nanoframework/hex2dfu)
3. holding the GameMode key and plug in the USB cable to enter DFU mode (the LOGO led will blink)
4. download the .dfu file into the MCU using DFUSe, (https://github.com/lingex/ST-DFUSe/releases)

**Comment by t3st-account** [comment]
ok thanks that did not work, as I am on Linux.
But I managed to use the hexfile to flash via STM32CubeProgrammer via dfu.

Thanks a lot for your information. I think i will be able to implement the HID package conversion and UART transmission on my own.
On the esp32 side of the project I will be using: [this](https://github.com/asterics/esp32_mouse_keyboard/) project by asterics
