### ISSUE TITLE
Is there a way to implement keystroke macros?

### ISSUE THREAD

**Issue by hyzx86** [lingex/G610Rebuild#5]
请教大佬，

自定义固件无法使用键盘宏，有什么别的方法实现么？ 

苦逼程序员要手撸很多密码，不能复制粘贴 而且又臭又长，G601 官方的的键盘宏 用一个就少一个 F功能键。。
对于程序员来说每个键都是有用的~~ 

比如 要为F2 录制宏

按下窗口+FN+【F2】  组合键 开始录制

再次按下窗口+FN+【F2】  组合键 结束录制

按键延迟标准50 就行

谢谢！

**Comment by hyzx86** [comment]
我这问题似乎解决了。。。
G切换这个功能就是干这个 用的， 这样的话 只牺牲一个F3 就行了~~

其它的 宏都可以通过按住F3 +  功能键触发

![image](https://user-images.githubusercontent.com/15613121/218139114-db4ba09d-257f-4d18-a3b1-ee34ee03ad30.png)

**Comment by lingex** [comment]
真要实现的话，这个单片机内置的 EEPROM 有 2k bytes 大小，目前存储参数大概用了十几字节，剩下的空间倒是可以用来录制，不过做不到100%利用，比如要考虑记录每个密码的起始位置等等。

从安全角度考虑，密码不应该存储在键盘中，何况你还是在连复制粘贴都不允许的情形下，这会是个很大的漏洞。

所以这需求还是使用官方软件达成比较好，没记错的话官方软件所有设置都是保存在电脑中的(这也是我不喜欢用它的原因, /lol).

**Comment by hyzx86** [comment]
中午好，

官方这个宏保存有点意思。。。
我有个键盘鼠标共享器硬件+软件，一个键盘鼠标控制两个电脑的，通过鼠标移动到左侧或者右侧边缘 自动切换到另外一个电脑
![image](https://user-images.githubusercontent.com/15613121/218236519-f1e6a01d-c72c-4f96-89d6-f1d895417fc0.png)
 
我个人电脑 是A  ，装软件不限制。
公司电脑B 各种限制安装软件。

我在A电脑上设置的宏，在切换到 B电脑上时可以直接用 - -

**Comment by lingex** [comment]
这么说有点像是记录在了键盘上(不能完全确定)。

我比较少用宏功能，实际上这个键盘也不怎么用了。买的比较早，当时只有茶轴，不太喜欢。最大的问题是键帽太糟，搞下卫生就各种弹飞，还是非标的，想自己换一套都买不到。

**Comment by hyzx86** [comment]
啊？ 我把坏的 的HP 键盘【FN】键 搞下来没啥毛病啊。
就是高了点，把腿削掉点就好了


旧的HP  GK100
![87e080502b868e32b4aef61323bf11e](https://user-images.githubusercontent.com/15613121/218244183-e4115b36-975f-46e4-8e58-0300001f4262.jpg)


换好后。。
![e9342aa2fe07dd8cfac4286f28a04a9](https://user-images.githubusercontent.com/15613121/218244179-d8fbf5f4-3ba0-4438-ac8a-ad085c970b45.jpg)

**Comment by hyzx86** [comment]
大佬有没有微信或者QQ  加个好友呗

我的wx是 hyzx86  QQ 51387245

**Comment by lingex** [comment]
那不是了，还得削短才好用，哪那么多功夫折腾。它的Ctrl、Shift等都跟市面上其它键盘不太一样。

**Comment by hyzx86** [comment]
嗯。。凑合用还行  我这也是刚入的 “官方二手” 🤣，京东广告点进去就入了
之前没想到有这些问题，就看上他自定义宏了
