### ISSUE TITLE
可以把右Win换成Fn吗

### ISSUE THREAD

**Issue by sjtuwater** [lingex/G610Rebuild#7]
买了新键帽，有菜单键，但不需要右win键，感觉保留全功能，多个菜单键也不坏事，能否把右win键改成Fn键呢？

**Comment by sjtuwater** [comment]
有以下几个问题，按住Fn+GameMode键，左上角的大G键闪烁，但是我的电脑里面没出现升级的U盘，并且DFUSEDemo无法检测到DFU设备

**Comment by sjtuwater** [comment]
希望可以添加更多的Fn功能键

**Comment by lingex** [comment]
> 有以下几个问题，按住Fn+GameMode键，左上角的大G键闪烁，但是我的电脑里面没出现升级的U盘，并且DFUSEDemo无法检测到DFU设备

DFU设备要装驱动，在设备管理器中查看，不是显示成U盘。

**Comment by sjtuwater** [comment]
可以添加更多的FN键功能吗。比如把Fn+F1=F13键，以此类推，让更多的键都可以定义功能，至于功能，可以用第三方的软件定义F13-F24对应的功能，作者可以留个联系方式吗

**Comment by sjtuwater** [comment]
或者出一个编译代码的教程啥的

**Comment by lingex** [comment]
由于 flash 大小原因 Bootloader 需要使用到商用软件，不方便过多介绍。

这个键盘我基本已经不用了且工作很忙，所以抱歉了
